
- name: Check to see if /mnt/galaxyIndices/genomes exists and if it doesn't create it.
  file: path=/mnt/galaxyIndices/genomes state=directory mode=0755 owner=galaxy group=users

- name: Create symlink to Galaxy genome indices
  file: state=link src=/mnt/galaxyIndices/genomes dest=/home/{{ new_user }}/galaxy_genomes owner={{ new_user }} group={{ new_user }} follow=False

- name: Create symlink to Galaxy app
  file: state=link src=/mnt/galaxy/galaxy-app dest=/home/{{ new_user }}/galaxy owner={{ new_user }} group={{ new_user }} follow=False

- name: Copy galaxy-fuse.py to new user home directory
  copy: src=galaxy-fuse.py dest=/home/{{ new_user }}/galaxy-fuse.py owner={{ new_user }} group={{ new_user }}
